#Turns on and off the hud for the mod
isModOn = true
#Turns on and off the streak boost effect
isEffectOn = true
#Percentage of strength increase per streak level. 5 is 5% more damage times the streak level (A streak level of 3 is 15% more damage with this).
# Default is 5
#Range: 0 ~ 1000
streakDamageBoostAmount = 5
#Time after a hit before a streak is erased
# Default is 15
#Range: 0 ~ 100
eraseStreakTime = 40
#If Erase Streak Time should increase exponentially as the streak is higher
isEraseStreakTimeExponential = true
#0 = hotbar, 1 = top left, 2 = top right, 3 = top middle, 4 = bottom left, 5 = bottom right
#Range: 0 ~ 5
hudLocation = 5
#The horizontal offset of the HUD (in pixels)
# Default is 5
#Range: -100 ~ 100
hudXPosition = -20
#The vertical offset of the HUD (in pixels)
# Default is 5
#Range: -100 ~ 100
hudYPosition = -8

