
[tools]
	customTypes = ["{\"name\": \"coin_engraving\", \"hasVariableMaterials\": false}", "{\"name\": \"singulize_potion\", \"hasVariableMaterials\": false}", "{\"name\": \"knives\", \"hasVariableMaterials\": false}"]

[worldGens]
	#Range: 0.0 ~ 1.0
	emptyColoniesGenerationChance = 0

